Initial commit,  empty project with minimal classes and tests
BIBSYSDEV/nva-persistence-utils pull request #1
Opened 2020-11-30 15:56 UTC by svenngjeto

2020-11-30 18:27 UTC, brinxmat requested changes

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/test/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandlerTest.java
> +    void handlerAcceptsSampleImportRequest() throws ApiGatewayException {
I guess assert does not throw

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/test/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandlerTest.java
> +    void handlerAcceptsSampleImportRequest() throws ApiGatewayException {
handlerAcceptsValidImportRequest?

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/test/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandlerTest.java
> +
For local variables, use `var`

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/test/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandlerTest.java
> +    void handlerReturnsAcceptedWhenInputIsOK() throws ApiGatewayException {
OK? IsValid? Does this test replace the first test above in practice?

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/test/java/no/unit/nva/model/utils/ExceptionsTest.java
> +public class ExceptionsTest {
I think this can be removed as we should test for the message in the handler test

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/main/java/no/unit/nva/model/utils/InputException.java
> +public class InputException extends ApiGatewayException {
Is there a more descriptive name that can be used for the exception?

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/main/java/no/unit/nva/model/utils/UpdatePersonIdentifierResponse.java
> +    public UpdatePersonIdentifierResponse(String message,
This looks oddly like "Problem", are you using it for problem responses too?

2020-11-30 18:27 UTC, brinxmat commented on dynamodb-converter/src/main/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandler.java
> +        if (Objects.isNull(input)) {
Static import of isNull

2020-12-02 12:25 UTC, axthosarouris commented on .gitignore
> +# User-specific stuff
add .idea/ to ignore the whole folder. And do a git rm -rf --cache .idea to remove and .idea files from git

2020-12-02 12:25 UTC, axthosarouris commented on datapipelineexport-reader/src/test/java/no/unit/nva/model/utils/UpdatePersonIdentifiersHandlerTest.java
> +        setupMockHandler().processInput(updatePersonIdentifierRequest, new RequestInfo(), mockContext);
I think this test is calling only the the mocked process "processInput". Do not mock processInput and test the hanlder using only the method handleRequest.

2021-03-03 08:58 UTC, closed without merging